In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
### Vocabulary size
voc_size=10000

#### One hot encoding of words

In [4]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8560, 7803, 1107, 1297], [8560, 7803, 1107, 5544], [8560, 124, 1107, 9078], [8141, 8854, 1280, 9585, 736], [8141, 8854, 1280, 9585, 4356], [1591, 8560, 7621, 1107, 2952], [8663, 4751, 2780, 9585]]


#### Word Embedding Representation 

In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

Pad all sentences with 0's at first to make length same

In [7]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8560 7803 1107 1297]
 [   0    0    0    0 8560 7803 1107 5544]
 [   0    0    0    0 8560  124 1107 9078]
 [   0    0    0 8141 8854 1280 9585  736]
 [   0    0    0 8141 8854 1280 9585 4356]
 [   0    0    0 1591 8560 7621 1107 2952]
 [   0    0    0    0 8663 4751 2780 9585]]


In [8]:
dim=10

In [14]:
model=Sequential()
# Embedding will be of size 10
model.add(Embedding(voc_size,10,input_length=sent_length))
#Adam optimizer , mean square error
model.compile('adam','mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [11]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 221ms/step
[[[-0.04457105  0.00304189  0.02365248 -0.00968846  0.03437135
   -0.00230373 -0.01760194  0.01551547 -0.02378956  0.03801247]
  [-0.04457105  0.00304189  0.02365248 -0.00968846  0.03437135
   -0.00230373 -0.01760194  0.01551547 -0.02378956  0.03801247]
  [-0.04457105  0.00304189  0.02365248 -0.00968846  0.03437135
   -0.00230373 -0.01760194  0.01551547 -0.02378956  0.03801247]
  [-0.04457105  0.00304189  0.02365248 -0.00968846  0.03437135
   -0.00230373 -0.01760194  0.01551547 -0.02378956  0.03801247]
  [-0.01505159  0.00128325 -0.02946809  0.00629852  0.00682155
   -0.04706696  0.04494223  0.00669115  0.01280904  0.04356123]
  [ 0.03255724 -0.00951078 -0.01894096  0.04777316 -0.01027257
   -0.03675659 -0.04848329  0.04111551 -0.03593631 -0.02476518]
  [-0.04005063  0.01303167  0.03873248  0.00879121 -0.00015197
    0.01439956  0.04812903  0.01941824 -0.01417843  0.02521208]
  [ 0.02013773  0.00877028  0.03814198 -0.03317974  0.0015

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 8560, 7803, 1107, 1297])

In [13]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 42ms/step
[[-0.04457105  0.00304189  0.02365248 -0.00968846  0.03437135 -0.00230373
  -0.01760194  0.01551547 -0.02378956  0.03801247]
 [-0.04457105  0.00304189  0.02365248 -0.00968846  0.03437135 -0.00230373
  -0.01760194  0.01551547 -0.02378956  0.03801247]
 [-0.04457105  0.00304189  0.02365248 -0.00968846  0.03437135 -0.00230373
  -0.01760194  0.01551547 -0.02378956  0.03801247]
 [-0.04457105  0.00304189  0.02365248 -0.00968846  0.03437135 -0.00230373
  -0.01760194  0.01551547 -0.02378956  0.03801247]
 [-0.01505159  0.00128325 -0.02946809  0.00629852  0.00682155 -0.04706696
   0.04494223  0.00669115  0.01280904  0.04356123]
 [ 0.03255724 -0.00951078 -0.01894096  0.04777316 -0.01027257 -0.03675659
  -0.04848329  0.04111551 -0.03593631 -0.02476518]
 [-0.04005063  0.01303167  0.03873248  0.00879121 -0.00015197  0.01439956
   0.04812903  0.01941824 -0.01417843  0.02521208]
 [ 0.02013773  0.00877028  0.03814198 -0.03317974  0.00151537 -0.04021584